//      Externalized Strings. English Version (en-US)
//      $Id: strings.js,v 1.22 2008/01/15 02:31:42 mjalvarez Exp $
//      (C)opyright Friendster Inc., 2003-2007

Locale['en-US'] = {
    'tryAgain' : 'Error. Please try again later.',
    'plsWait' : 'Please wait...',
    //comments and rating
    'loading' : 'loading',
    'fetchingComments': 'fetching comments',
    'noComments' : 'No Comments.',
    'tempUnavail' : 'temporarily unavailable.',
    'seeAllComments' : 'See All Comments',
    'deleteComment' : 'Delete Comment',
    'blockUser' : 'Block this User',
    'commentPosted' : 'posted',
    
    'alreadyCommented' : 'You have commented on this photo.',
    'disabledComments' : 'The owner of this photo has disabled comments.',
    'login2Comment' : 'You have to login to comment on this photo.',
    'cannotComment' : 'You cannot comment on this photo.',
    'first2rate' : 'be the first to rate!',
    'fetchingRating' : 'fetching rating',
    'ratings' : 'ratings',//plural
    'rating' : 'rating',
    'ratingSubmitted' : 'Your rating has been submitted.',
    'alreadyRated' : 'You have rated this photo.',
    'login2rate' : 'You have to login to rate this photo.',
    'cannotRate' : 'You cannot rate this photo.',
    'disabledRating' : 'The owner of this photo has disabled ratings.',
    'editTitle' : 'Click here to edit title',
    'primaryPhoto' : 'Primary Photo',
    'setPrimaryPhoto' : 'Set As Primary Photo',
    'uploadedBy' : 'Uploaded By',
    'grabbedFrom' : 'Grabbed from',
    'shareProfile' : 'Share this profile',
    //location.js
    'selectCity' : 'Select City',
    'selectState' : 'Select State/Province',
    //footer.js
    'sponsorLinks' : 'Sponsored Links',
    'haveBlog' : 'Do you have a blog?',
    'haveRss' : 'Do you have a favorite RSS feed?',
    'showFriends' : 'Would you like to show it to your friends?',
    'enterRss1' : 'Get started by entering the ',
    'enterRss2' : 'RSS field in your profile.',
    'errorRss1' : 'We are not able to process the RSS feed URL you specified in your profile.  Please ',
    'errorRss2' : 'check the URL',
    'errorRss3' : ' for accuracy.  For more information on RSS feeds, please ',
    'errorRss4' : 'read this.',
    'blog' : 'Blog',
    'viewBlog' : 'View Blog',
    'help' : 'Help',
    'recentPost' : 'Recent Posts',
    'seeAllPost' : 'see all posts',
    'posted' : 'Posted',
    //friendster_v1.js
    'smon' : 'Mon',
    'stue' : 'Tue',
    'swed' : 'Wed',
    'sthu' : 'Thu',
    'sfri' : 'Fri',
    'ssat' : 'Sat',
    'ssun' : 'Sun',
    'lmon' : 'Monday',
    'ltue' : 'Tuesday',
    'lwed' : 'Wednesday',
    'lthu' : 'Thursday',
    'lfri' : 'Friday',
    'lsat' : 'Saturday',
    'lsun' : 'Sunday',
    'ljan' : 'January',
    'lfeb' : 'February',
    'lmar' : 'March',
    'lapr' : 'April',
    'lmay' : 'May',
    'ljun' : 'June',
    'ljul' : 'July',
    'laug' : 'August',
    'lsep' : 'September',
    'loct' : 'October',
    'lnov' : 'November',
    'ldec' : 'December',
    'sjan' : 'Jan',
    'sfeb' : 'Feb',
    'smar' : 'Mar',
    'sapr' : 'Apr',
    'smay' : 'May',
    'sjun' : 'Jun',
    'sjul' : 'Jul',
    'saug' : 'Aug',
    'ssep' : 'Sep',
    'soct' : 'Oct',
    'snov' : 'Nov',
    'sdec' : 'Dec',
    //home.js
    'single' : 'Single',
    'inARel' : 'In a Relationship',
    'married' : 'Married',
    'domPar' : 'Domestic Partnership',
    'complicated' : 'It\'s Complicated',
    'featureTempUnavail' : 'This feature is temporarily unavailable. Try checking back in a couple of minutes.',
    //invite.js
    'alreadyInFriendster' : 'are already on Friendster.',
    'seeWhoYouKnow' : 'See who you know.',
    'peopleFrom' : 'people from',
    //modules_friendster.js
    'noContent' : 'No content found.',
    //pandora.js
    'radioTopShared' : 'Top Shared Stations ',
    'viewMore' : 'view more',
    'myStations' : 'My Stations',
    'stationPossesive' : '\'s Stations',
    'details' : 'Details',
    'buyOnAmazon' : 'Buy on Amazon',
    'buyOniTunes' : 'Buy on iTunes',
    'latestFavSong' : 'Latest Favorite Songs',
    //school.js
    // :TODO:
    // 'Error! Not enough function arguments (<number>, excluding the string)\nfor the number of substitution parameters in string (<number> so far).'
    // 'Error! Not enough function arguments (' + (arguments.length - 1) + ', excluding the string)\nfor the number of substitution parameters in string (' + numSubstitutions + ' so far).'
    'selectCountry' : 'Select your country',
    //topfriends.js
    'removeFrmList' : 'Remove from list.',
    'featuredFriendFull' : 'All Featured Friends slots are taken.  Remove one from the list to add a new friend.',
    'featuredFriendAdd' : 'Add to list.',
    //videos.js
    'checkOut' : 'Check this out on Friendster!',
    'loadingVideos' : 'Loading videos...',
    'problemloadingVids' : 'A problem may have occured while loading the videos...  Please try again.',
    'uploadUrOwnVids' : 'Upload Your Own Video',
    'moreVidsOn' : ' More Videos on ',


	// tracker timestamps (home.js)   
    'hoursAgo' : 'hours ago',
    'hourAgo' : 'hour ago',
    'secondsAgo' : 'seconds ago',
    'secondAgo' : 'second ago',
	'minutesAgo' : 'minutes ago',
	'minuteAgo' : 'minute ago',
    'daysAgo' : 'days ago',
    'dayAgo' : 'day ago',
    'weeksAgo' : 'weeks ago',
    'weekAgo' : 'week ago',
    'monthsAgo' : 'months ago',
    'monthAgo' : 'month ago',
    'yearsAgo' : 'years ago',
    'yearAgo' : 'year ago',
    'momentsAgo' : 'moments ago',
    
	// Fancy Upload
	'maxPhotosReached' : 'Max Photos Reached',
	'filesizeFailure' : 'Upload failed, please check your filesize',
	'invalidTarget' : 'Invalid target, please reload page and try again',
	'unsupportedMedia' : 'Unsupported media type, please upload GIF, PNG, TIFF or JPEG',
    'cantProcessImage' : 'Upload failed. Could not process image',
    'internalServerError' : 'Upload failed. Unable to process image',
    'completedUpload' : 'Completed',
    'removeFromQueue' : 'Remove from queue',
    'fileTooBig' : 'The selected file is too big',

    //Schools Redesign
    'emptySchoolName' : 'Please select a Country and Type a School Name',
    'emptyStartYr' : 'Choose a Start Year',
    'emptyEndYr' : 'Choose an End Year',
    'InvalidYrs' : 'Invalid Start and End year',
    'emptyRegion' : 'Please select a State or Province',
    'emptyCity' : 'Please select a City',
    'schoolNotFound' : 'School Not Found',
    'addSchoolNotice' : 'Click here to submit your school for review',
    'dropDownNotice' : 'Please select an option or school from the drop down menu',
    //End: Schools Redesign

	'uploading' : 'Uploading',
	'reachedMaxPhotos' : 'You have reached your photo upload limit.',
	'any' : 'Any',

    // Albums
	'slideAutoPlay' : 'Auto Play',	
    'slidePause' : 'Pause',		
    'privacyPublic' : 'Public',
    'privacyPrivate' : 'Private',
    'editAlbumSuccess' : 'Update album successful! Changes will be reflected after page is reloaded.',
    'editAlbumFail' : 'Private',    
	'albumHeader' : 'Album Properties',	
    'editAlbumName' : 'Name',
    'editAlbumDesc' : 'Description',        
    'editAlbumPriv' : 'Privacy',            
    'editAlbumSaving' : 'Saving changes...',            
    'editAlbumLoading' : 'Loading album properties...',
    'editAlbumNameCannotBeEmpty' : 'Album name cannot be empty.',  
    'editAlbumFailedToLoad' : 'Album details failed to load. Please try again later',
    'submit1Degree' : 'First-degree friends',
    'submit2Degree' : 'First and Second-degree friends',
    'nobody' : 'No one',
    'submiLeveltLabel': 'Who can upload photos to this album',
    'myPublicPhotos' : 'My Public Photos',
    'myPrivatePhotos' : 'My Private Photos',
    'grabbingPhoto' : 'Grabbing photo...',
    'unselectAll' : 'Unselect All',
    'selectAll' : 'Select All'
};






